const bikeCatalog = {
  Ducati: {
    logo: "../img/foto_moto/ducati/logo/Ducati_red_logo.svg.png",
    Cross: {
      bike1: {
        id: 37,
        name: "Desmo450 MX",
        cilindrata: "449 cc",
        potenza: "63.5 HP",
        prezzo: "€15.000+",
        img: "../img/foto_moto/ducati/cross/Desmo450 MX.jpg",
      },
      bike2: {
        id: 38,
        name: "Hypermotard 698 Mono RVE",
        cilindrata: "659 cc",
        potenza: "77.5 HP",
        prezzo: "€14.495",
        img: "../img/foto_moto/ducati/cross/Hypermotard-698-Mono-RVE.png",
      },
      bike3: {
        id: 39,
        name: "Desmo250 MX",
        cilindrata: "250 cc",
        potenza: "40+ HP",
        prezzo: "€10.000+",
        img: "../img/foto_moto/ducati/cross/Desmo450 MX.jpg",
      },
    },
    Naked: {
      bike1: {
        id: 43,
        name: "Streetfighter V2 S",
        cilindrata: "890 cc",
        potenza: "120 HP",
        prezzo: "€18.995",
        img: "../img/foto_moto/ducati/naked/Streetfighter V2 S.png",
      },
      bike2: {
        id: 44,
        name: "Diavel for Bentley",
        cilindrata: "1.158 cc",
        potenza: "168 HP",
        prezzo: "€70.000",
        img: "../img/foto_moto/ducati/naked/Diavel for Bentley.jpg",
      },
      bike3: {
        id: 45,
        name: "Ducati Streetfighter V4 Supreme",
        cilindrata: "1.103 cc",
        potenza: "208 HP",
        prezzo: "€50.000",
        img: "../img/foto_moto/ducati/naked/Ducati Streetfighter V4 Supreme.jpg",
      },
    },
    Sportive: {
      bike1: {
        id: 40,
        name: "Panigale V2",
        cilindrata: "890 cc",
        potenza: "120 HP",
        prezzo: "€19.120",
        img: "../img/foto_moto/ducati/sportive/Panigale V2.webp",
      },
      bike2: {
        id: 41,
        name: "Ducati Unica",
        cilindrata: "V4 1.103 cc",
        potenza: "215+ HP",
        prezzo: "€50.000+",
        img: "../img/foto_moto/ducati/sportive/Ducati Unica.png",
      },
      bike3: {
        id: 42,
        name: "Panigale V4 Lamborghini",
        cilindrata: "1.103 cc",
        potenza: "218.5 HP",
        prezzo: "€78.400",
        img: "../img/foto_moto/ducati/sportive/Panigale V4 Lamborghini.jpg",
      },
    },
  },

  Honda: {
    logo: "../img/foto_moto/honda/logo/honda-11-logo-png-transparent.png",
    Cross: {
      bike1: {
        id: 1,
        name: "CRF 450RWE 2026",
        cilindrata: "450 cc",
        potenza: "52.6 HP (39.2 kW)",
        prezzo: "€12.599",
        img: "../img/foto_moto/honda/cross/CRF 450RWE 2026.png",
      },
      bike2: {
        id: 2,
        name: "CRF 450R SMT 2026",
        cilindrata: "450 cc",
        potenza: "52.6 HP (39.2 kW)",
        prezzo: "€9.699",
        img: "../img/foto_moto/honda/cross/CRF 450R SMT 2026.png",
      },
      bike3: {
        id: 3,
        name: "CRF 450RX Rally 2026",
        cilindrata: "450 cc",
        potenza: "52.6 HP (39.2 kW)",
        prezzo: "€9.999",
        img: "../img/foto_moto/honda/cross/CRF 450RX Rally.jpeg",
      },
    },
    Naked: {
      bike1: {
        id: 7,
        name: "CB1000 Hornet",
        cilindrata: "1.000 cc",
        potenza: "150 HP (111.6 kW)",
        prezzo: "€9.099",
        img: "../img/foto_moto/honda/naked/CB1000 Hornet.jpg",
      },
      bike2: {
        id: 8,
        name: "CB750 Hornet",
        cilindrata: "755 cc",
        potenza: "91 HP (67.5 kW)",
        prezzo: "€8.000+",
        img: "../img/foto_moto/honda/naked/CB750 Hornet.png",
      },
      bike3: {
        id: 9,
        name: "CB1000R BLACK EDITION",
        cilindrata: "998 cc",
        potenza: "109 HP (81.61 kW)",
        prezzo: "€15.000+",
        img: "../img/foto_moto/honda/naked/CB1000R BLACK EDITION.png",
      },
    },
    Sportive: {
      bike1: {
        id: 4,
        name: "CBR1000RR-R Fireblade SP Carbon Edition",
        cilindrata: "1.000 cc",
        potenza: "218 HP (162 kW)",
        prezzo: "€30.000+",
        img: "../img/foto_moto/honda/sportive/CBR1000RR-R Fireblade SP Carbon Edition.jpg",
      },
      bike2: {
        id: 5,
        name: "CBR650R",
        cilindrata: "649 cc",
        potenza: "94 HP (70 kW)",
        prezzo: "€11.160",
        img: "../img/foto_moto/honda/sportive/CBR650R.png",
      },
      bike3: {
        id: 6,
        name: "CBR600RR",
        cilindrata: "599 cc",
        potenza: "119 HP (89 kW)",
        prezzo: "€15.000+",
        img: "../img/foto_moto/honda/sportive/CBR600RR.png",
      },
    },
  },

  Kawasaki: {
    logo: "../img/foto_moto/Kawasaki/logo/kawasaki-logo-free-png-701751694711254up3hnwgg9p.png",
    Cross: {
      bike1: {
        id: 10,
        name: "KX450",
        cilindrata: "449 cc",
        potenza: "56 HP (41 kW)",
        prezzo: "€9.500+",
        img: "../img/foto_moto/Kawasaki/cross/KX450.png",
      },
      bike2: {
        id: 11,
        name: "KX250",
        cilindrata: "249 cc",
        potenza: "42 HP (31.3 kW)",
        prezzo: "€8.000+",
        img: "../img/foto_moto/Kawasaki/cross/KX250.png",
      },
      bike3: {
        id: 12,
        name: "KX450X",
        cilindrata: "449 cc",
        potenza: "56 HP (41 kW)",
        prezzo: "€10.699",
        img: "../img/foto_moto/Kawasaki/cross/KX450X.png",
      },
    },
    Naked: {
      bike1: {
        id: 16,
        name: "Z H2 SE",
        cilindrata: "998 cc",
        potenza: "197 HP (147 kW)",
        prezzo: "€21.300",
        img: "../img/foto_moto/Kawasaki/naked/Z H2 SE.png",
      },
      bike2: {
        id: 17,
        name: "Z900",
        cilindrata: "948 cc",
        potenza: "123 HP (92 kW)",
        prezzo: "€9.990",
        img: "../img/foto_moto/Kawasaki/naked/Z900.png",
      },
      bike3: {
        id: 18,
        name: "Z1100",
        cilindrata: "1.099 cc",
        potenza: "134 HP (99 kW)",
        prezzo: "€14.999",
        img: "../img/foto_moto/Kawasaki/naked/Z1100.png",
      },
    },
    Sportive: {
      bike1: {
        id: 13,
        name: "Ninja H2R",
        cilindrata: "998 cc",
        potenza: "310 HP (230 kW)",
        prezzo: "€50.000+",
        img: "../img/foto_moto/Kawasaki/sportive/Ninja H2R.png",
      },
      bike2: {
        id: 14,
        name: "Ninja ZX-10RR",
        cilindrata: "998 cc",
        potenza: "200+ HP (148 kW)",
        prezzo: "€25.000+",
        img: "../img/foto_moto/Kawasaki/sportive/Ninja ZX-10RR.png",
      },
      bike3: {
        id: 15,
        name: "Ninja 650",
        cilindrata: "649 cc",
        potenza: "67 HP (50 kW)",
        prezzo: "€8.299",
        img: "../img/foto_moto/Kawasaki/sportive/Ninja 650.png",
      },
    },
  },

  KTM: {
    logo: "../img/foto_moto/KTM/logo/KTM-logo.png",
    Cross: {
      bike1: {
        id: 19,
        name: "2026 KTM 300 SX",
        cilindrata: "293 cc (2T)",
        potenza: "49.1 HP (36.6 kW)",
        prezzo: "€9.000+",
        img: "../img/foto_moto/KTM/cross/2026 KTM 300 SX.png",
      },
      bike2: {
        id: 20,
        name: "2026 KTM 450 SX-F FACTORY EDITION",
        cilindrata: "450 cc",
        potenza: "60+ HP",
        prezzo: "€12.000+",
        img: "../img/foto_moto/KTM/cross/2026 KTM 450 SX-F FACTORY EDITION.png",
      },
      bike3: {
        id: 21,
        name: "2026 KTM 450 SMR",
        cilindrata: "450 cc",
        potenza: "63 HP (46.7 kW)",
        prezzo: "€12.499",
        img: "../img/foto_moto/KTM/cross/2026 KTM 450 SMR.png",
      },
    },
    Naked: {
      bike1: {
        id: 25,
        name: "2026 BRABUS 1400 R SIGNATURE EDITION",
        cilindrata: "1.350 cc",
        potenza: "190 HP (140 kW)",
        prezzo: "€50.000+",
        img: "../img/foto_moto/KTM/naked/2026 BRABUS 1400 R SIGNATURE EDITION.jpg",
      },
      bike2: {
        id: 26,
        name: "2026 KTM 1390 Super Duke R EVO",
        cilindrata: "1.350 cc",
        potenza: "190 HP (140 kW)",
        prezzo: "€21.790+",
        img: "../img/foto_moto/KTM/naked/2026 KTM 1390 Super Duke R EVO.jpg",
      },
      bike3: {
        id: 27,
        name: "2025 KTM 125 Duke",
        cilindrata: "124 cc",
        potenza: "15 HP (11 kW)",
        prezzo: "€1.750",
        img: "../img/foto_moto/KTM/naked/2025 KTM 125 Duke.png",
      },
    },
    Sportive: {
      bike1: {
        id: 22,
        name: "2026 KTM 990 RC R",
        cilindrata: "947 cc",
        potenza: "128 HP (94 kW)",
        prezzo: "€13.949",
        img: "../img/foto_moto/KTM/sportive/2026 KTM 990 RC R.jpg",
      },
      bike2: {
        id: 23,
        name: "2024 KTM RC 390",
        cilindrata: "373 cc",
        potenza: "43 HP (32 kW)",
        prezzo: "€5.899",
        img: "../img/foto_moto/KTM/sportive/2024 KTM RC 390.jpg",
      },
      bike3: {
        id: 24,
        name: "2024 KTM RC 125",
        cilindrata: "124 cc",
        potenza: "15 HP (11 kW)",
        prezzo: "€5.000+",
        img: "../img/foto_moto/KTM/sportive/2024 KTM RC 125.jpg",
      },
    },
  },

  Suzuki: {
    logo: "../img/foto_moto/suzuki/logo/Suzuki_logo_2025_(vertical).svg.png",
    Cross: {
      bike1: {
        id: 46,
        name: "RM-Z450",
        cilindrata: "449 cc",
        potenza: "56 HP",
        prezzo: "€9.399",
        img: "../img/foto_moto/suzuki/cross/RM-Z450.jpg",
      },
      bike2: {
        id: 47,
        name: "DR-Z4S",
        cilindrata: "398 cc",
        potenza: "37 HP",
        prezzo: "€7.500+",
        img: "../img/foto_moto/suzuki/cross/DR-Z4S.jpg",
      },
      bike3: {
        id: 48,
        name: "DR-Z4SM",
        cilindrata: "398 cc",
        potenza: "37 HP",
        prezzo: "€7.500+",
        img: "../img/foto_moto/suzuki/cross/DR-Z4SM.jpg",
      },
    },
    Naked: {
      bike1: {
        id: 52,
        name: "GSX-S1000 EVO",
        cilindrata: "999 cc",
        potenza: "150 HP",
        prezzo: "€14.000+",
        img: "../img/foto_moto/suzuki/naked/GSX-S1000 EVO.jpg",
      },
      bike2: {
        id: 53,
        name: "KATANA",
        cilindrata: "999 cc",
        potenza: "150 HP",
        prezzo: "€13.499",
        img: "../img/foto_moto/suzuki/naked/KATANA.jpg",
      },
      bike3: {
        id: 54,
        name: "SV650",
        cilindrata: "645 cc",
        potenza: "75 HP",
        prezzo: "€7.500+",
        img: "../img/foto_moto/suzuki/naked/SV650.jpg",
      },
    },
    Sportive: {
      bike1: {
        id: 49,
        name: "HAYABUSA",
        cilindrata: "1.340 cc",
        potenza: "190 HP",
        prezzo: "€18.060",
        img: "../img/foto_moto/suzuki/sportive/HAYABUSA.png",
      },
      bike2: {
        id: 50,
        name: "GSX-R1000R",
        cilindrata: "999 cc",
        potenza: "200+ HP",
        prezzo: "€18.649",
        img: "../img/foto_moto/suzuki/sportive/GSX-R1000R.jpg",
      },
      bike3: {
        id: 51,
        name: "GSX-8R EVO",
        cilindrata: "776 cc",
        potenza: "81.8 HP",
        prezzo: "€9.439",
        img: "../img/foto_moto/suzuki/sportive/GSX-8R EVO.jpg",
      },
    },
  },

  Yamaha: {
    logo: "../img/foto_moto/yamaha/logo/yamaha-3d-logo-png_seeklogo-289364.png",
    Cross: {
      bike1: {
        id: 28,
        name: "YZ450F 70th Anniversary Edition",
        cilindrata: "450 cc",
        potenza: "60+ HP",
        prezzo: "€10.499",
        img: "../img/foto_moto/yamaha/cross/YZ450F 70th Anniversary Edition.jpg",
      },
      bike2: {
        id: 29,
        name: "YZ250F Monster Energy Yamaha Racing Edition",
        cilindrata: "250 cc",
        potenza: "40+ HP",
        prezzo: "€9.099",
        img: "../img/foto_moto/yamaha/cross/YZ250F Monster Energy Yamaha Racing Edition.jpg",
      },
      bike3: {
        id: 30,
        name: "YZ125",
        cilindrata: "125 cc (2T)",
        potenza: "35 HP",
        prezzo: "€7.199",
        img: "../img/foto_moto/yamaha/cross/YZ125.jpg",
      },
    },
    Naked: {
      bike1: {
        id: 34,
        name: "MT-10",
        cilindrata: "998 cc",
        potenza: "166 HP",
        prezzo: "€15.000+",
        img: "../img/foto_moto/yamaha/naked/MT-10.jpg",
      },
      bike2: {
        id: 35,
        name: "MT-09 SP",
        cilindrata: "890 cc",
        potenza: "119 HP",
        prezzo: "€13.900",
        img: "../img/foto_moto/yamaha/naked/MT-09 SP.jpg",
      },
      bike3: {
        id: 36,
        name: "MT-125",
        cilindrata: "125 cc",
        potenza: "15 HP",
        prezzo: "€5.251",
        img: "../img/foto_moto/yamaha/naked/MT-125.jpg",
      },
    },
    Sportive: {
      bike1: {
        id: 31,
        name: "XSR900 GP",
        cilindrata: "890 cc",
        potenza: "119 HP (88 kW)",
        prezzo: "€12.000+",
        img: "../img/foto_moto/yamaha/sportive/XSR900 GP.jpg",
      },
      bike2: {
        id: 32,
        name: "R1 RACE",
        cilindrata: "998 cc",
        potenza: "200 HP",
        prezzo: "€25.000+",
        img: "../img/foto_moto/yamaha/sportive/R1 RACE.jpg",
      },
      bike3: {
        id: 33,
        name: "R6 GYTR",
        cilindrata: "599 cc",
        potenza: "118 HP",
        prezzo: "€20.000+",
        img: "../img/foto_moto/yamaha/sportive/R6 GYTR.jpg",
      },
    },
  },
};
